#ifndef _SYSCALLNUMBER_H
#define _SYSCALLNUMBER_H

#define __NR_io_setup 0
#define __NR_io_destroy 1
#define __NR_io_submit 2
#define __NR_io_cancel 3
#define __NR_io_getevents 4
#define __NR_setxattr 5
#define __NR_lsetxattr 6
#define __NR_fsetxattr 7
#define __NR_getxattr 8
#define __NR_lgetxattr 9
#define __NR_fgetxattr 10
#define __NR_listxattr 11
#define __NR_llistxattr 12
#define __NR_flistxattr 13
#define __NR_removexattr 14
#define __NR_lremovexattr 15
#define __NR_fremovexattr 16
#define __NR_getcwd 17
#define __NR_lookup_dcookie 18
#define __NR_eventfd2 19
#define __NR_epoll_create1 20
#define __NR_epoll_ctl 21
#define __NR_epoll_pwait 22
#define __NR_dup 23
#define __NR_dup3 24
#define __NR3264_fcntl 25
#define __NR_inotify_init1 26
#define __NR_inotify_add_watch 27
#define __NR_inotify_rm_watch 28
#define __NR_ioctl 29
#define __NR_ioprio_set 30
#define __NR_ioprio_get 31
#define __NR_flock 32
#define __NR_mknodat 33
#define __NR_mkdirat 34
#define __NR_unlinkat 35
#define __NR_symlinkat 36
#define __NR_linkat 37
#define __NR_renameat 38
#define __NR_umount2 39
#define __NR_mount 40
#define __NR_pivot_root 41
#define __NR_nfsservctl 42
#define __NR3264_statfs 43
#define __NR3264_fstatfs 44
#define __NR3264_truncate 45
#define __NR3264_ftruncate 46
#define __NR_fallocate 47
#define __NR_faccessat 48
#define __NR_chdir 49
#define __NR_fchdir 50
#define __NR_chroot 51
#define __NR_fchmod 52
#define __NR_fchmodat 53
#define __NR_fchownat 54
#define __NR_fchown 55
#define __NR_openat 56
#define __NR_close 57
#define __NR_vhangup 58
#define __NR_pipe2 59
#define __NR_quotactl 60
#define __NR_getdents64 61
#define __NR3264_lseek 62
#define __NR_read 63
#define __NR_write 64
#define __NR_readv 65
#define __NR_writev 66
#define __NR_pread64 67
#define __NR_pwrite64 68
#define __NR_preadv 69
#define __NR_pwritev 70
#define __NR3264_sendfile 71
#define __NR_pselect6 72
#define __NR_ppoll 73
#define __NR_signalfd4 74
#define __NR_vmsplice 75
#define __NR_splice 76
#define __NR_tee 77
#define __NR_readlinkat 78
#define __NR3264_fstatat 79
#define __NR3264_fstat 80
#define __NR_sync 81
#define __NR_fsync 82
#define __NR_fdatasync 83
#define __NR_sync_file_range2 84
#define __NR_sync_file_range 84
#define __NR_timerfd_create 85
#define __NR_timerfd_settime 86
#define __NR_timerfd_gettime 87
#define __NR_utimensat 88
#define __NR_acct 89
#define __NR_capget 90
#define __NR_capset 91
#define __NR_personality 92
#define __NR_exit 93
#define __NR_exit_group 94
#define __NR_waitid 95
#define __NR_set_tid_address 96
#define __NR_unshare 97
#define __NR_futex 98
#define __NR_set_robust_list 99
#define __NR_get_robust_list 100
#define __NR_nanosleep 101
#define __NR_getitimer 102
#define __NR_setitimer 103
#define __NR_kexec_load 104
#define __NR_init_module 105
#define __NR_delete_module 106
#define __NR_timer_create 107
#define __NR_timer_gettime 108
#define __NR_timer_getoverrun 109
#define __NR_timer_settime 110
#define __NR_timer_delete 111
#define __NR_clock_settime 112
#define __NR_clock_gettime 113
#define __NR_clock_getres 114
#define __NR_clock_nanosleep 115
#define __NR_syslog 116
#define __NR_ptrace 117
#define __NR_sched_setparam 118
#define __NR_sched_setscheduler 119
#define __NR_sched_getscheduler 120
#define __NR_sched_getparam 121
#define __NR_sched_setaffinity 122
#define __NR_sched_getaffinity 123
#define __NR_sched_yield 124
#define __NR_sched_get_priority_max 125
#define __NR_sched_get_priority_min 126
#define __NR_sched_rr_get_interval 127
#define __NR_restart_syscall 128
#define __NR_kill 129
#define __NR_tkill 130
#define __NR_tgkill 131
#define __NR_sigaltstack 132
#define __NR_rt_sigsuspend 133
#define __NR_rt_sigaction 134
#define __NR_rt_sigprocmask 135
#define __NR_rt_sigpending 136
#define __NR_rt_sigtimedwait 137
#define __NR_rt_sigqueueinfo 138
#define __NR_rt_sigreturn 139
#define __NR_setpriority 140
#define __NR_getpriority 141
#define __NR_reboot 142
#define __NR_setregid 143
#define __NR_setgid 144
#define __NR_setreuid 145
#define __NR_setuid 146
#define __NR_setresuid 147
#define __NR_getresuid 148
#define __NR_setresgid 149
#define __NR_getresgid 150
#define __NR_setfsuid 151
#define __NR_setfsgid 152
#define __NR_times 153
#define __NR_setpgid 154
#define __NR_getpgid 155
#define __NR_getsid 156
#define __NR_setsid 157
#define __NR_getgroups 158
#define __NR_setgroups 159
#define __NR_uname 160
#define __NR_sethostname 161
#define __NR_setdomainname 162
#define __NR_getrlimit 163
#define __NR_setrlimit 164
#define __NR_getrusage 165
#define __NR_umask 166
#define __NR_prctl 167
#define __NR_getcpu 168
#define __NR_gettimeofday 169
#define __NR_settimeofday 170
#define __NR_adjtimex 171
#define __NR_getpid 172
#define __NR_getppid 173
#define __NR_getuid 174
#define __NR_geteuid 175
#define __NR_getgid 176
#define __NR_getegid 177
#define __NR_gettid 178
#define __NR_sysinfo 179
#define __NR_mq_open 180
#define __NR_mq_unlink 181
#define __NR_mq_timedsend 182
#define __NR_mq_timedreceive 183
#define __NR_mq_notify 184
#define __NR_mq_getsetattr 185
#define __NR_msgget 186
#define __NR_msgctl 187
#define __NR_msgrcv 188
#define __NR_msgsnd 189
#define __NR_semget 190
#define __NR_semctl 191
#define __NR_semtimedop 192
#define __NR_semop 193
#define __NR_shmget 194
#define __NR_shmctl 195
#define __NR_shmat 196
#define __NR_shmdt 197
#define __NR_socket 198
#define __NR_socketpair 199
#define __NR_bind 200
#define __NR_listen 201
#define __NR_accept 202
#define __NR_connect 203
#define __NR_getsockname 204
#define __NR_getpeername 205
#define __NR_sendto 206
#define __NR_recvfrom 207
#define __NR_setsockopt 208
#define __NR_getsockopt 209
#define __NR_shutdown 210
#define __NR_sendmsg 211
#define __NR_recvmsg 212
#define __NR_readahead 213
#define __NR_brk 214
#define __NR_munmap 215
#define __NR_mremap 216
#define __NR_add_key 217
#define __NR_request_key 218
#define __NR_keyctl 219
#define __NR_clone 220
#define __NR_execve 221
#define __NR3264_mmap 222
#define __NR3264_fadvise64 223
#define __NR_swapon 224
#define __NR_swapoff 225
#define __NR_mprotect 226
#define __NR_msync 227
#define __NR_mlock 228
#define __NR_munlock 229
#define __NR_mlockall 230
#define __NR_munlockall 231
#define __NR_mincore 232
#define __NR_madvise 233
#define __NR_remap_file_pages 234
#define __NR_mbind 235
#define __NR_get_mempolicy 236
#define __NR_set_mempolicy 237
#define __NR_migrate_pages 238
#define __NR_move_pages 239
#define __NR_rt_tgsigqueueinfo 240
#define __NR_perf_event_open 241
#define __NR_accept4 242
#define __NR_recvmmsg 243
#define __NR_arch_specific_syscall 244
#define __NR_wait4 260
#define __NR_prlimit64 261
#define __NR_fanotify_init 262
#define __NR_fanotify_mark 263
#define __NR_name_to_handle_at         264
#define __NR_open_by_handle_at         265
#define __NR_clock_adjtime 266
#define __NR_syncfs 267
#define __NR_setns 268
#define __NR_sendmmsg 269
#define __NR_process_vm_readv 270
#define __NR_process_vm_writev 271
#define __NR_kcmp 272
#define __NR_finit_module 273
#define __NR_sched_setattr 274
#define __NR_sched_getattr 275
#define __NR_renameat2 276
#define __NR_seccomp 277
#define __NR_getrandom 278
#define __NR_memfd_create 279
#define __NR_bpf 280
#define __NR_execveat 281
#define __NR_userfaultfd 282
#define __NR_membarrier 283
#define __NR_mlock2 284
#define __NR_copy_file_range 285
#define __NR_preadv2 286
#define __NR_pwritev2 287
#define __NR_pkey_mprotect 288
#define __NR_pkey_alloc 289
#define __NR_pkey_free 290
#define __NR_statx 291
#define __NR_io_pgetevents 292
#define __NR_rseq 293
#define __NR_kexec_file_load 294
#define __NR_clock_gettime64 403
#define __NR_clock_settime64 404
#define __NR_clock_adjtime64 405
#define __NR_clock_getres_time64 406
#define __NR_clock_nanosleep_time64 407
#define __NR_timer_gettime64 408
#define __NR_timer_settime64 409
#define __NR_timerfd_gettime64 410
#define __NR_timerfd_settime64 411
#define __NR_utimensat_time64 412
#define __NR_pselect6_time64 413
#define __NR_ppoll_time64 414
#define __NR_io_pgetevents_time64 416
#define __NR_recvmmsg_time64 417
#define __NR_mq_timedsend_time64 418
#define __NR_mq_timedreceive_time64 419
#define __NR_semtimedop_time64 420
#define __NR_rt_sigtimedwait_time64 421
#define __NR_futex_time64 422
#define __NR_sched_rr_get_interval_time64 423
#define __NR_pidfd_send_signal 424
#define __NR_io_uring_setup 425
#define __NR_io_uring_enter 426
#define __NR_io_uring_register 427
#define __NR_open_tree 428
#define __NR_move_mount 429
#define __NR_fsopen 430
#define __NR_fsconfig 431
#define __NR_fsmount 432
#define __NR_fspick 433
#define __NR_pidfd_open 434
#define __NR_clone3 435
#define __NR_close_range 436
#define __NR_openat2 437
#define __NR_pidfd_getfd 438
#define __NR_faccessat2 439
#define __NR_process_madvise 440
#define __NR_epoll_pwait2 441
#define __NR_mount_setattr 442
#define __NR_quotactl_fd 443
#define __NR_landlock_create_ruleset 444
#define __NR_landlock_add_rule 445
#define __NR_landlock_restrict_self 446
#define __NR_memfd_secret 447
#define __NR_process_mrelease 448
#define __NR_futex_waitv 449
#define __NR_set_mempolicy_home_node 450
#undef __NR_syscalls
#define __NR_syscalls 451

#if __BITS_PER_LONG == 64 && !defined(__SYSCALL_COMPAT)
#define __NR_fcntl __NR3264_fcntl
#define __NR_statfs __NR3264_statfs
#define __NR_fstatfs __NR3264_fstatfs
#define __NR_truncate __NR3264_truncate
#define __NR_ftruncate __NR3264_ftruncate
#define __NR_lseek __NR3264_lseek
#define __NR_sendfile __NR3264_sendfile
#if defined(__ARCH_WANT_NEW_STAT) || defined(__ARCH_WANT_STAT64)
#define __NR_newfstatat __NR3264_fstatat
#define __NR_fstat __NR3264_fstat
#endif
#define __NR_mmap __NR3264_mmap
#define __NR_fadvise64 __NR3264_fadvise64
#ifdef __NR3264_stat
#define __NR_stat __NR3264_stat
#define __NR_lstat __NR3264_lstat
#endif
#else
#define __NR_fcntl64 __NR3264_fcntl
#define __NR_statfs64 __NR3264_statfs
#define __NR_fstatfs64 __NR3264_fstatfs
#define __NR_truncate64 __NR3264_truncate
#define __NR_ftruncate64 __NR3264_ftruncate
#define __NR_llseek __NR3264_lseek
#define __NR_sendfile64 __NR3264_sendfile
#if defined(__ARCH_WANT_NEW_STAT) || defined(__ARCH_WANT_STAT64)
#define __NR_fstatat64 __NR3264_fstatat
#define __NR_fstat64 __NR3264_fstat
#endif
#define __NR_mmap2 __NR3264_mmap
#define __NR_fadvise64_64 __NR3264_fadvise64
#ifdef __NR3264_stat
#define __NR_stat64 __NR3264_stat
#define __NR_lstat64 __NR3264_lstat
#endif
#endif

#define STR(x) #x

const char *syscall_name[] = {
[__NR_io_setup] = STR(io_setup),
[__NR_io_destroy] = STR(io_destroy),
[__NR_io_submit] = STR(io_submit),
[__NR_io_cancel] = STR(io_cancel),
[__NR_io_getevents] = STR(io_getevents),
[__NR_setxattr] = STR(setxattr),
[__NR_lsetxattr] = STR(lsetxattr),
[__NR_fsetxattr] = STR(fsetxattr),
[__NR_getxattr] = STR(getxattr),
[__NR_lgetxattr] = STR(lgetxattr),
[__NR_fgetxattr] = STR(fgetxattr),
[__NR_listxattr] = STR(listxattr),
[__NR_llistxattr] = STR(llistxattr),
[__NR_flistxattr] = STR(flistxattr),
[__NR_removexattr] = STR(removexattr),
[__NR_lremovexattr] = STR(lremovexattr),
[__NR_fremovexattr] = STR(fremovexattr),
[__NR_getcwd] = STR(getcwd),
[__NR_lookup_dcookie] = STR(lookup_dcookie),
[__NR_eventfd2] = STR(eventfd2),
[__NR_epoll_create1] = STR(epoll_create1),
[__NR_epoll_ctl] = STR(epoll_ctl),
[__NR_epoll_pwait] = STR(epoll_pwait),
[__NR_dup] = STR(dup),
[__NR_dup3] = STR(dup3),
[__NR3264_fcntl] = STR(__NR3264_fcntl),
[__NR_inotify_init1] = STR(inotify_init1),
[__NR_inotify_add_watch] = STR(inotify_add_watch),
[__NR_inotify_rm_watch] = STR(inotify_rm_watch),
[__NR_ioctl] = STR(ioctl),
[__NR_ioprio_set] = STR(ioprio_set),
[__NR_ioprio_get] = STR(ioprio_get),
[__NR_flock] = STR(flock),
[__NR_mknodat] = STR(mknodat),
[__NR_mkdirat] = STR(mkdirat),
[__NR_unlinkat] = STR(unlinkat),
[__NR_symlinkat] = STR(symlinkat),
[__NR_linkat] = STR(linkat),
[__NR_renameat] = STR(renameat),
[__NR_umount2] = STR(umount2),
[__NR_mount] = STR(mount),
[__NR_pivot_root] = STR(pivot_root),
[__NR_nfsservctl] = STR(nfsservctl),
[__NR3264_statfs] = STR(__NR3264_statfs),
[__NR3264_fstatfs] = STR(__NR3264_fstatfs),
[__NR3264_truncate] = STR(__NR3264_truncate),
[__NR3264_ftruncate] = STR(__NR3264_ftruncate),
[__NR_fallocate] = STR(fallocate),
[__NR_faccessat] = STR(faccessat),
[__NR_chdir] = STR(chdir),
[__NR_fchdir] = STR(fchdir),
[__NR_chroot] = STR(chroot),
[__NR_fchmod] = STR(fchmod),
[__NR_fchmodat] = STR(fchmodat),
[__NR_fchownat] = STR(fchownat),
[__NR_fchown] = STR(fchown),
[__NR_openat] = STR(openat),
[__NR_close] = STR(close),
[__NR_vhangup] = STR(vhangup),
[__NR_pipe2] = STR(pipe2),
[__NR_quotactl] = STR(quotactl),
[__NR_getdents64] = STR(getdents64),
[__NR3264_lseek] = STR(__NR3264_lseek),
[__NR_read] = STR(read),
[__NR_write] = STR(write),
[__NR_readv] = STR(readv),
[__NR_writev] = STR(writev),
[__NR_pread64] = STR(pread64),
[__NR_pwrite64] = STR(pwrite64),
[__NR_preadv] = STR(preadv),
[__NR_pwritev] = STR(pwritev),
[__NR3264_sendfile] = STR(__NR3264_sendfile),
[__NR_pselect6] = STR(pselect6),
[__NR_ppoll] = STR(ppoll),
[__NR_signalfd4] = STR(signalfd4),
[__NR_vmsplice] = STR(vmsplice),
[__NR_splice] = STR(splice),
[__NR_tee] = STR(tee),
[__NR_readlinkat] = STR(readlinkat),
[__NR3264_fstatat] = STR(__NR3264_fstatat),
[__NR3264_fstat] = STR(__NR3264_fstat),
[__NR_sync] = STR(sync),
[__NR_fsync] = STR(fsync),
[__NR_fdatasync] = STR(fdatasync),
[__NR_sync_file_range2] = STR(sync_file_range2),
[__NR_sync_file_range] = STR(sync_file_range),
[__NR_timerfd_create] = STR(timerfd_create),
[__NR_timerfd_settime] = STR(timerfd_settime),
[__NR_timerfd_gettime] = STR(timerfd_gettime),
[__NR_utimensat] = STR(utimensat),
[__NR_acct] = STR(acct),
[__NR_capget] = STR(capget),
[__NR_capset] = STR(capset),
[__NR_personality] = STR(personality),
[__NR_exit] = STR(exit),
[__NR_exit_group] = STR(exit_group),
[__NR_waitid] = STR(waitid),
[__NR_set_tid_address] = STR(set_tid_address),
[__NR_unshare] = STR(unshare),
[__NR_futex] = STR(futex),
[__NR_set_robust_list] = STR(set_robust_list),
[__NR_get_robust_list] = STR(get_robust_list),
[__NR_nanosleep] = STR(nanosleep),
[__NR_getitimer] = STR(getitimer),
[__NR_setitimer] = STR(setitimer),
[__NR_kexec_load] = STR(kexec_load),
[__NR_init_module] = STR(init_module),
[__NR_delete_module] = STR(delete_module),
[__NR_timer_create] = STR(timer_create),
[__NR_timer_gettime] = STR(timer_gettime),
[__NR_timer_getoverrun] = STR(timer_getoverrun),
[__NR_timer_settime] = STR(timer_settime),
[__NR_timer_delete] = STR(timer_delete),
[__NR_clock_settime] = STR(clock_settime),
[__NR_clock_gettime] = STR(clock_gettime),
[__NR_clock_getres] = STR(clock_getres),
[__NR_clock_nanosleep] = STR(clock_nanosleep),
[__NR_syslog] = STR(syslog),
[__NR_ptrace] = STR(ptrace),
[__NR_sched_setparam] = STR(sched_setparam),
[__NR_sched_setscheduler] = STR(sched_setscheduler),
[__NR_sched_getscheduler] = STR(sched_getscheduler),
[__NR_sched_getparam] = STR(sched_getparam),
[__NR_sched_setaffinity] = STR(sched_setaffinity),
[__NR_sched_getaffinity] = STR(sched_getaffinity),
[__NR_sched_yield] = STR(sched_yield),
[__NR_sched_get_priority_max] = STR(sched_get_priority_max),
[__NR_sched_get_priority_min] = STR(sched_get_priority_min),
[__NR_sched_rr_get_interval] = STR(sched_rr_get_interval),
[__NR_restart_syscall] = STR(restart_syscall),
[__NR_kill] = STR(kill),
[__NR_tkill] = STR(tkill),
[__NR_tgkill] = STR(tgkill),
[__NR_sigaltstack] = STR(sigaltstack),
[__NR_rt_sigsuspend] = STR(rt_sigsuspend),
[__NR_rt_sigaction] = STR(rt_sigaction),
[__NR_rt_sigprocmask] = STR(rt_sigprocmask),
[__NR_rt_sigpending] = STR(rt_sigpending),
[__NR_rt_sigtimedwait] = STR(rt_sigtimedwait),
[__NR_rt_sigqueueinfo] = STR(rt_sigqueueinfo),
[__NR_rt_sigreturn] = STR(rt_sigreturn),
[__NR_setpriority] = STR(setpriority),
[__NR_getpriority] = STR(getpriority),
[__NR_reboot] = STR(reboot),
[__NR_setregid] = STR(setregid),
[__NR_setgid] = STR(setgid),
[__NR_setreuid] = STR(setreuid),
[__NR_setuid] = STR(setuid),
[__NR_setresuid] = STR(setresuid),
[__NR_getresuid] = STR(getresuid),
[__NR_setresgid] = STR(setresgid),
[__NR_getresgid] = STR(getresgid),
[__NR_setfsuid] = STR(setfsuid),
[__NR_setfsgid] = STR(setfsgid),
[__NR_times] = STR(times),
[__NR_setpgid] = STR(setpgid),
[__NR_getpgid] = STR(getpgid),
[__NR_getsid] = STR(getsid),
[__NR_setsid] = STR(setsid),
[__NR_getgroups] = STR(getgroups),
[__NR_setgroups] = STR(setgroups),
[__NR_uname] = STR(uname),
[__NR_sethostname] = STR(sethostname),
[__NR_setdomainname] = STR(setdomainname),
[__NR_getrlimit] = STR(getrlimit),
[__NR_setrlimit] = STR(setrlimit),
[__NR_getrusage] = STR(getrusage),
[__NR_umask] = STR(umask),
[__NR_prctl] = STR(prctl),
[__NR_getcpu] = STR(getcpu),
[__NR_gettimeofday] = STR(gettimeofday),
[__NR_settimeofday] = STR(settimeofday),
[__NR_adjtimex] = STR(adjtimex),
[__NR_getpid] = STR(getpid),
[__NR_getppid] = STR(getppid),
[__NR_getuid] = STR(getuid),
[__NR_geteuid] = STR(geteuid),
[__NR_getgid] = STR(getgid),
[__NR_getegid] = STR(getegid),
[__NR_gettid] = STR(gettid),
[__NR_sysinfo] = STR(sysinfo),
[__NR_mq_open] = STR(mq_open),
[__NR_mq_unlink] = STR(mq_unlink),
[__NR_mq_timedsend] = STR(mq_timedsend),
[__NR_mq_timedreceive] = STR(mq_timedreceive),
[__NR_mq_notify] = STR(mq_notify),
[__NR_mq_getsetattr] = STR(mq_getsetattr),
[__NR_msgget] = STR(msgget),
[__NR_msgctl] = STR(msgctl),
[__NR_msgrcv] = STR(msgrcv),
[__NR_msgsnd] = STR(msgsnd),
[__NR_semget] = STR(semget),
[__NR_semctl] = STR(semctl),
[__NR_semtimedop] = STR(semtimedop),
[__NR_semop] = STR(semop),
[__NR_shmget] = STR(shmget),
[__NR_shmctl] = STR(shmctl),
[__NR_shmat] = STR(shmat),
[__NR_shmdt] = STR(shmdt),
[__NR_socket] = STR(socket),
[__NR_socketpair] = STR(socketpair),
[__NR_bind] = STR(bind),
[__NR_listen] = STR(listen),
[__NR_accept] = STR(accept),
[__NR_connect] = STR(connect),
[__NR_getsockname] = STR(getsockname),
[__NR_getpeername] = STR(getpeername),
[__NR_sendto] = STR(sendto),
[__NR_recvfrom] = STR(recvfrom),
[__NR_setsockopt] = STR(setsockopt),
[__NR_getsockopt] = STR(getsockopt),
[__NR_shutdown] = STR(shutdown),
[__NR_sendmsg] = STR(sendmsg),
[__NR_recvmsg] = STR(recvmsg),
[__NR_readahead] = STR(readahead),
[__NR_brk] = STR(brk),
[__NR_munmap] = STR(munmap),
[__NR_mremap] = STR(mremap),
[__NR_add_key] = STR(add_key),
[__NR_request_key] = STR(request_key),
[__NR_keyctl] = STR(keyctl),
[__NR_clone] = STR(clone),
[__NR_execve] = STR(execve),
[__NR3264_mmap] = STR(__NR3264_mmap),
[__NR3264_fadvise64] = STR(__NR3264_fadvise64),
[__NR_swapon] = STR(swapon),
[__NR_swapoff] = STR(swapoff),
[__NR_mprotect] = STR(mprotect),
[__NR_msync] = STR(msync),
[__NR_mlock] = STR(mlock),
[__NR_munlock] = STR(munlock),
[__NR_mlockall] = STR(mlockall),
[__NR_munlockall] = STR(munlockall),
[__NR_mincore] = STR(mincore),
[__NR_madvise] = STR(madvise),
[__NR_remap_file_pages] = STR(remap_file_pages),
[__NR_mbind] = STR(mbind),
[__NR_get_mempolicy] = STR(get_mempolicy),
[__NR_set_mempolicy] = STR(set_mempolicy),
[__NR_migrate_pages] = STR(migrate_pages),
[__NR_move_pages] = STR(move_pages),
[__NR_rt_tgsigqueueinfo] = STR(rt_tgsigqueueinfo),
[__NR_perf_event_open] = STR(perf_event_open),
[__NR_accept4] = STR(accept4),
[__NR_recvmmsg] = STR(recvmmsg),
[__NR_arch_specific_syscall] = STR(arch_specific_syscall),
[__NR_wait4] = STR(wait4),
[__NR_prlimit64] = STR(prlimit64),
[__NR_fanotify_init] = STR(fanotify_init),
[__NR_fanotify_mark] = STR(fanotify_mark),
[__NR_name_to_handle_at] = STR(name_to_handle_at),
[__NR_open_by_handle_at] = STR(open_by_handle_at),
[__NR_clock_adjtime] = STR(clock_adjtime),
[__NR_syncfs] = STR(syncfs),
[__NR_setns] = STR(setns),
[__NR_sendmmsg] = STR(sendmmsg),
[__NR_process_vm_readv] = STR(process_vm_readv),
[__NR_process_vm_writev] = STR(process_vm_writev),
[__NR_kcmp] = STR(kcmp),
[__NR_finit_module] = STR(finit_module),
[__NR_sched_setattr] = STR(sched_setattr),
[__NR_sched_getattr] = STR(sched_getattr),
[__NR_renameat2] = STR(renameat2),
[__NR_seccomp] = STR(seccomp),
[__NR_getrandom] = STR(getrandom),
[__NR_memfd_create] = STR(memfd_create),
[__NR_bpf] = STR(bpf),
[__NR_execveat] = STR(execveat),
[__NR_userfaultfd] = STR(userfaultfd),
[__NR_membarrier] = STR(membarrier),
[__NR_mlock2] = STR(mlock2),
[__NR_copy_file_range] = STR(copy_file_range),
[__NR_preadv2] = STR(preadv2),
[__NR_pwritev2] = STR(pwritev2),
[__NR_pkey_mprotect] = STR(pkey_mprotect),
[__NR_pkey_alloc] = STR(pkey_alloc),
[__NR_pkey_free] = STR(pkey_free),
[__NR_statx] = STR(statx),
[__NR_io_pgetevents] = STR(io_pgetevents),
[__NR_rseq] = STR(rseq),
[__NR_kexec_file_load] = STR(kexec_file_load),
[__NR_clock_gettime64] = STR(clock_gettime64),
[__NR_clock_settime64] = STR(clock_settime64),
[__NR_clock_adjtime64] = STR(clock_adjtime64),
[__NR_clock_getres_time64] = STR(clock_getres_time64),
[__NR_clock_nanosleep_time64] = STR(clock_nanosleep_time64),
[__NR_timer_gettime64] = STR(timer_gettime64),
[__NR_timer_settime64] = STR(timer_settime64),
[__NR_timerfd_gettime64] = STR(timerfd_gettime64),
[__NR_timerfd_settime64] = STR(timerfd_settime64),
[__NR_utimensat_time64] = STR(utimensat_time64),
[__NR_pselect6_time64] = STR(pselect6_time64),
[__NR_ppoll_time64] = STR(ppoll_time64),
[__NR_io_pgetevents_time64] = STR(io_pgetevents_time64),
[__NR_recvmmsg_time64] = STR(recvmmsg_time64),
[__NR_mq_timedsend_time64] = STR(mq_timedsend_time64),
[__NR_mq_timedreceive_time64] = STR(mq_timedreceive_time64),
[__NR_semtimedop_time64] = STR(semtimedop_time64),
[__NR_rt_sigtimedwait_time64] = STR(rt_sigtimedwait_time64),
[__NR_futex_time64] = STR(futex_time64),
[__NR_sched_rr_get_interval_time64] = STR(sched_rr_get_interval_time64),
[__NR_pidfd_send_signal] = STR(pidfd_send_signal),
[__NR_io_uring_setup] = STR(io_uring_setup),
[__NR_io_uring_enter] = STR(io_uring_enter),
[__NR_io_uring_register] = STR(io_uring_register),
[__NR_open_tree] = STR(open_tree),
[__NR_move_mount] = STR(move_mount),
[__NR_fsopen] = STR(fsopen),
[__NR_fsconfig] = STR(fsconfig),
[__NR_fsmount] = STR(fsmount),
[__NR_fspick] = STR(fspick),
[__NR_pidfd_open] = STR(pidfd_open),
[__NR_clone3] = STR(clone3),
[__NR_close_range] = STR(close_range),
[__NR_openat2] = STR(openat2),
[__NR_pidfd_getfd] = STR(pidfd_getfd),
[__NR_faccessat2] = STR(faccessat2),
[__NR_process_madvise] = STR(process_madvise),
[__NR_epoll_pwait2] = STR(epoll_pwait2),
[__NR_mount_setattr] = STR(mount_setattr),
[__NR_quotactl_fd] = STR(quotactl_fd),
[__NR_landlock_create_ruleset] = STR(landlock_create_ruleset),
[__NR_landlock_add_rule] = STR(landlock_add_rule),
[__NR_landlock_restrict_self] = STR(landlock_restrict_self),
[__NR_memfd_secret] = STR(memfd_secret),
[__NR_process_mrelease] = STR(process_mrelease),
[__NR_futex_waitv] = STR(futex_waitv),
[__NR_set_mempolicy_home_node] = STR(set_mempolicy_home_node),
[__NR_syscalls] = STR(syscalls),
};

/*
const char *syscall_name[] = {
[__NR_read] = STR(read),
[__NR_write] = STR(write),
[__NR_open] = STR(open),
[__NR_close] = STR(close),
[__NR_stat] = STR(stat),
[__NR_fstat] = STR(fstat),
[__NR_lstat] = STR(lstat),
[__NR_poll] = STR(poll),
[__NR_lseek] = STR(lseek),
[__NR_mmap] = STR(mmap),
[__NR_mprotect] = STR(mprotect),
[__NR_munmap] = STR(munmap),
[__NR_brk] = STR(brk),
[__NR_rt_sigaction] = STR(rt_sigaction),
[__NR_rt_sigprocmask] = STR(rt_sigprocmask),
[__NR_rt_sigreturn] = STR(rt_sigreturn),
[__NR_ioctl] = STR(ioctl),
[__NR_pread64] = STR(pread64),
[__NR_pwrite64] = STR(pwrite64),
[__NR_readv] = STR(readv),
[__NR_writev] = STR(writev),
[__NR_access] = STR(access),
[__NR_pipe] = STR(pipe),
[__NR_select] = STR(select),
[__NR_sched_yield] = STR(sched_yield),
[__NR_mremap] = STR(mremap),
[__NR_msync] = STR(msync),
[__NR_mincore] = STR(mincore),
[__NR_madvise] = STR(madvise),
[__NR_shmget] = STR(shmget),
[__NR_shmat] = STR(shmat),
[__NR_shmctl] = STR(shmctl),
[__NR_dup] = STR(dup),
[__NR_dup] = STR(dup),
[__NR_pause] = STR(pause),
[__NR_nanosleep] = STR(nanosleep),
[__NR_getitimer] = STR(getitimer),
[__NR_alarm] = STR(alarm),
[__NR_setitimer] = STR(setitimer),
[__NR_getpid] = STR(getpid),
[__NR_sendfile] = STR(sendfile),
[__NR_socket] = STR(socket),
[__NR_connect] = STR(connect),
[__NR_accept] = STR(accept),
[__NR_sendto] = STR(sendto),
[__NR_recvfrom] = STR(recvfrom),
[__NR_sendmsg] = STR(sendmsg),
[__NR_recvmsg] = STR(recvmsg),
[__NR_shutdown] = STR(shutdown),
[__NR_bind] = STR(bind),
[__NR_listen] = STR(listen),
[__NR_getsockname] = STR(getsockname),
[__NR_getpeername] = STR(getpeername),
[__NR_socketpair] = STR(socketpair),
[__NR_setsockopt] = STR(setsockopt),
[__NR_getsockopt] = STR(getsockopt),
[__NR_clone] = STR(clone),
[__NR_fork] = STR(fork),
[__NR_vfork] = STR(vfork),
[__NR_execve] = STR(execve),
[__NR_exit] = STR(exit),
[__NR_wait4] = STR(wait4),
[__NR_kill] = STR(kill),
[__NR_uname] = STR(uname),
[__NR_semget] = STR(semget),
[__NR_semop] = STR(semop),
[__NR_semctl] = STR(semctl),
[__NR_shmdt] = STR(shmdt),
[__NR_msgget] = STR(msgget),
[__NR_msgsnd] = STR(msgsnd),
[__NR_msgrcv] = STR(msgrcv),
[__NR_msgctl] = STR(msgctl),
[__NR_fcntl] = STR(fcntl),
[__NR_flock] = STR(flock),
[__NR_fsync] = STR(fsync),
[__NR_fdatasync] = STR(fdatasync),
[__NR_truncate] = STR(truncate),
[__NR_ftruncate] = STR(ftruncate),
[__NR_getdents] = STR(getdents),
[__NR_getcwd] = STR(getcwd),
[__NR_chdir] = STR(chdir),
[__NR_fchdir] = STR(fchdir),
[__NR_rename] = STR(rename),
[__NR_mkdir] = STR(mkdir),
[__NR_rmdir] = STR(rmdir),
[__NR_creat] = STR(creat),
[__NR_link] = STR(link),
[__NR_unlink] = STR(unlink),
[__NR_symlink] = STR(symlink),
[__NR_readlink] = STR(readlink),
[__NR_chmod] = STR(chmod),
[__NR_fchmod] = STR(fchmod),
[__NR_chown] = STR(chown),
[__NR_fchown] = STR(fchown),
[__NR_lchown] = STR(lchown),
[__NR_umask] = STR(umask),
[__NR_gettimeofday] = STR(gettimeofday),
[__NR_getrlimit] = STR(getrlimit),
[__NR_getrusage] = STR(getrusage),
[__NR_sysinfo] = STR(sysinfo),
[__NR_times] = STR(times),
[__NR_ptrace] = STR(ptrace),
[__NR_getuid] = STR(getuid),
[__NR_syslog] = STR(syslog),
[__NR_getgid] = STR(getgid),
[__NR_setuid] = STR(setuid),
[__NR_setgid] = STR(setgid),
[__NR_geteuid] = STR(geteuid),
[__NR_getegid] = STR(getegid),
[__NR_setpgid] = STR(setpgid),
[__NR_getppid] = STR(getppid),
[__NR_getpgrp] = STR(getpgrp),
[__NR_setsid] = STR(setsid),
[__NR_setreuid] = STR(setreuid),
[__NR_setregid] = STR(setregid),
[__NR_getgroups] = STR(getgroups),
[__NR_setgroups] = STR(setgroups),
[__NR_setresuid] = STR(setresuid),
[__NR_getresuid] = STR(getresuid),
[__NR_setresgid] = STR(setresgid),
[__NR_getresgid] = STR(getresgid),
[__NR_getpgid] = STR(getpgid),
[__NR_setfsuid] = STR(setfsuid),
[__NR_setfsgid] = STR(setfsgid),
[__NR_getsid] = STR(getsid),
[__NR_capget] = STR(capget),
[__NR_capset] = STR(capset),
[__NR_rt_sigpending] = STR(rt_sigpending),
[__NR_rt_sigtimedwait] = STR(rt_sigtimedwait),
[__NR_rt_sigqueueinfo] = STR(rt_sigqueueinfo),
[__NR_rt_sigsuspend] = STR(rt_sigsuspend),
[__NR_sigaltstack] = STR(sigaltstack),
[__NR_utime] = STR(utime),
[__NR_mknod] = STR(mknod),
[__NR_uselib] = STR(uselib),
[__NR_personality] = STR(personality),
[__NR_ustat] = STR(ustat),
[__NR_statfs] = STR(statfs),
[__NR_fstatfs] = STR(fstatfs),
[__NR_sysfs] = STR(sysfs),
[__NR_getpriority] = STR(getpriority),
[__NR_setpriority] = STR(setpriority),
[__NR_sched_setparam] = STR(sched_setparam),
[__NR_sched_getparam] = STR(sched_getparam),
[__NR_sched_setscheduler] = STR(sched_setscheduler),
[__NR_sched_getscheduler] = STR(sched_getscheduler),
[__NR_sched_get_priority_max] = STR(sched_get_priority_max),
[__NR_sched_get_priority_min] = STR(sched_get_priority_min),
[__NR_sched_rr_get_interval] = STR(sched_rr_get_interval),
[__NR_mlock] = STR(mlock),
[__NR_munlock] = STR(munlock),
[__NR_mlockall] = STR(mlockall),
[__NR_munlockall] = STR(munlockall),
[__NR_vhangup] = STR(vhangup),
[__NR_modify_ldt] = STR(modify_ldt),
[__NR_pivot_root] = STR(pivot_root),
[__NR__sysctl] = STR(_sysctl),
[__NR_prctl] = STR(prctl),
[__NR_arch_prctl] = STR(arch_prctl),
[__NR_adjtimex] = STR(adjtimex),
[__NR_setrlimit] = STR(setrlimit),
[__NR_chroot] = STR(chroot),
[__NR_sync] = STR(sync),
[__NR_acct] = STR(acct),
[__NR_settimeofday] = STR(settimeofday),
[__NR_mount] = STR(mount),
[__NR_umount2] = STR(umount2),
[__NR_swapon] = STR(swapon),
[__NR_swapoff] = STR(swapoff),
[__NR_reboot] = STR(reboot),
[__NR_sethostname] = STR(sethostname),
[__NR_setdomainname] = STR(setdomainname),
[__NR_iopl] = STR(iopl),
[__NR_ioperm] = STR(ioperm),
[__NR_create_module] = STR(create_module),
[__NR_init_module] = STR(init_module),
[__NR_delete_module] = STR(delete_module),
[__NR_get_kernel_syms] = STR(get_kernel_syms),
[__NR_query_module] = STR(query_module),
[__NR_quotactl] = STR(quotactl),
[__NR_nfsservctl] = STR(nfsservctl),
[__NR_getpmsg] = STR(getpmsg),
[__NR_putpmsg] = STR(putpmsg),
[__NR_afs_syscall] = STR(afs_syscall),
[__NR_tuxcall] = STR(tuxcall),
[__NR_security] = STR(security),
[__NR_gettid] = STR(gettid),
[__NR_readahead] = STR(readahead),
[__NR_setxattr] = STR(setxattr),
[__NR_lsetxattr] = STR(lsetxattr),
[__NR_fsetxattr] = STR(fsetxattr),
[__NR_getxattr] = STR(getxattr),
[__NR_lgetxattr] = STR(lgetxattr),
[__NR_fgetxattr] = STR(fgetxattr),
[__NR_listxattr] = STR(listxattr),
[__NR_llistxattr] = STR(llistxattr),
[__NR_flistxattr] = STR(flistxattr),
[__NR_removexattr] = STR(removexattr),
[__NR_lremovexattr] = STR(lremovexattr),
[__NR_fremovexattr] = STR(fremovexattr),
[__NR_tkill] = STR(tkill),
[__NR_time] = STR(time),
[__NR_futex] = STR(futex),
[__NR_sched_setaffinity] = STR(sched_setaffinity),
[__NR_sched_getaffinity] = STR(sched_getaffinity),
[__NR_set_thread_area] = STR(set_thread_area),
[__NR_io_setup] = STR(io_setup),
[__NR_io_destroy] = STR(io_destroy),
[__NR_io_getevents] = STR(io_getevents),
[__NR_io_submit] = STR(io_submit),
[__NR_io_cancel] = STR(io_cancel),
[__NR_get_thread_area] = STR(get_thread_area),
[__NR_lookup_dcookie] = STR(lookup_dcookie),
[__NR_epoll_create] = STR(epoll_create),
[__NR_epoll_ctl_old] = STR(epoll_ctl_old),
[__NR_epoll_wait_old] = STR(epoll_wait_old),
[__NR_remap_file_pages] = STR(remap_file_pages),
[__NR_getdents] = STR(getdents),
[__NR_set_tid_address] = STR(set_tid_address),
[__NR_restart_syscall] = STR(restart_syscall),
[__NR_semtimedop] = STR(semtimedop),
[__NR_fadvise64] = STR(fadvise64),
[__NR_timer_create] = STR(timer_create),
[__NR_timer_settime] = STR(timer_settime),
[__NR_timer_gettime] = STR(timer_gettime),
[__NR_timer_getoverrun] = STR(timer_getoverrun),
[__NR_timer_delete] = STR(timer_delete),
[__NR_clock_settime] = STR(clock_settime),
[__NR_clock_gettime] = STR(clock_gettime),
[__NR_clock_getres] = STR(clock_getres),
[__NR_clock_nanosleep] = STR(clock_nanosleep),
[__NR_exit_group] = STR(exit_group),
[__NR_epoll_wait] = STR(epoll_wait),
[__NR_epoll_ctl] = STR(epoll_ctl),
[__NR_tgkill] = STR(tgkill),
[__NR_utimes] = STR(utimes),
[__NR_vserver] = STR(vserver),
[__NR_mbind] = STR(mbind),
[__NR_set_mempolicy] = STR(set_mempolicy),
[__NR_get_mempolicy] = STR(get_mempolicy),
[__NR_mq_open] = STR(mq_open),
[__NR_mq_unlink] = STR(mq_unlink),
[__NR_mq_timedsend] = STR(mq_timedsend),
[__NR_mq_timedreceive] = STR(mq_timedreceive),
[__NR_mq_notify] = STR(mq_notify),
[__NR_mq_getsetattr] = STR(mq_getsetattr),
[__NR_kexec_load] = STR(kexec_load),
[__NR_waitid] = STR(waitid),
[__NR_add_key] = STR(add_key),
[__NR_request_key] = STR(request_key),
[__NR_keyctl] = STR(keyctl),
[__NR_ioprio_set] = STR(ioprio_set),
[__NR_ioprio_get] = STR(ioprio_get),
[__NR_inotify_init] = STR(inotify_init),
[__NR_inotify_add_watch] = STR(inotify_add_watch),
[__NR_inotify_rm_watch] = STR(inotify_rm_watch),
[__NR_migrate_pages] = STR(migrate_pages),
[__NR_openat] = STR(openat),
[__NR_mkdirat] = STR(mkdirat),
[__NR_mknodat] = STR(mknodat),
[__NR_fchownat] = STR(fchownat),
[__NR_futimesat] = STR(futimesat),
[__NR_newfstatat] = STR(newfstatat),
[__NR_unlinkat] = STR(unlinkat),
[__NR_renameat] = STR(renameat),
[__NR_linkat] = STR(linkat),
[__NR_symlinkat] = STR(symlinkat),
[__NR_readlinkat] = STR(readlinkat),
[__NR_fchmodat] = STR(fchmodat),
[__NR_faccessat] = STR(faccessat),
[__NR_pselect6] = STR(pselect6),
[__NR_ppoll] = STR(ppoll),
[__NR_unshare] = STR(unshare),
[__NR_set_robust_list] = STR(set_robust_list),
[__NR_get_robust_list] = STR(get_robust_list),
[__NR_splice] = STR(splice),
[__NR_tee] = STR(tee),
[__NR_sync_file_range] = STR(sync_file_range),
[__NR_vmsplice] = STR(vmsplice),
[__NR_move_pages] = STR(move_pages),
[__NR_utimensat] = STR(utimensat),
[__NR_epoll_pwait] = STR(epoll_pwait),
[__NR_signalfd] = STR(signalfd),
[__NR_timerfd_create] = STR(timerfd_create),
[__NR_eventfd] = STR(eventfd),
[__NR_fallocate] = STR(fallocate),
[__NR_timerfd_settime] = STR(timerfd_settime),
[__NR_timerfd_gettime] = STR(timerfd_gettime),
[__NR_accept] = STR(accept),
[__NR_signalfd] = STR(signalfd),
[__NR_eventfd] = STR(eventfd),
[__NR_epoll_create] = STR(epoll_create),
[__NR_dup] = STR(dup),
[__NR_pipe] = STR(pipe),
[__NR_inotify_init] = STR(inotify_init),
[__NR_preadv] = STR(preadv),
[__NR_pwritev] = STR(pwritev),
[__NR_rt_tgsigqueueinfo] = STR(rt_tgsigqueueinfo),
[__NR_perf_event_open] = STR(perf_event_open),
[__NR_recvmmsg] = STR(recvmmsg),
[__NR_fanotify_init] = STR(fanotify_init),
[__NR_fanotify_mark] = STR(fanotify_mark),
[__NR_prlimit64] = STR(prlimit64),
[__NR_name_to_handle_at] = STR(name_to_handle_at),
[__NR_open_by_handle_at] = STR(open_by_handle_at),
[__NR_clock_adjtime] = STR(clock_adjtime),
[__NR_syncfs] = STR(syncfs),
[__NR_sendmmsg] = STR(sendmmsg),
[__NR_setns] = STR(setns),
[__NR_getcpu] = STR(getcpu),
[__NR_process_vm_readv] = STR(process_vm_readv),
[__NR_process_vm_writev] = STR(process_vm_writev),
[__NR_kcmp] = STR(kcmp),
[__NR_finit_module] = STR(finit_module),
[__NR_sched_setattr] = STR(sched_setattr),
[__NR_sched_getattr] = STR(sched_getattr),
[__NR_renameat] = STR(renameat),
[__NR_seccomp] = STR(seccomp),
[__NR_getrandom] = STR(getrandom),
[__NR_memfd_create] = STR(memfd_create),
[__NR_kexec_file_load] = STR(kexec_file_load),
[__NR_bpf] = STR(bpf),
[__NR_execveat] = STR(execveat),
[__NR_userfaultfd] = STR(userfaultfd),
[__NR_membarrier] = STR(membarrier),
[__NR_mlock] = STR(mlock),
[__NR_copy_file_range] = STR(copy_file_range),
[__NR_preadv] = STR(preadv),
[__NR_pwritev] = STR(pwritev),
[__NR_pkey_mprotect] = STR(pkey_mprotect),
[__NR_pkey_alloc] = STR(pkey_alloc),
[__NR_pkey_free] = STR(pkey_free),
[__NR_statx] = STR(statx),
[__NR_io_pgetevents] = STR(io_pgetevents),
[__NR_rseq] = STR(rseq),
[__NR_pidfd_send_signal] = STR(pidfd_send_signal),
[__NR_io_uring_setup] = STR(io_uring_setup),
[__NR_io_uring_enter] = STR(io_uring_enter),
[__NR_io_uring_register] = STR(io_uring_register),
[__NR_open_tree] = STR(open_tree),
[__NR_move_mount] = STR(move_mount),
[__NR_fsopen] = STR(fsopen),
[__NR_fsconfig] = STR(fsconfig),
[__NR_fsmount] = STR(fsmount),
[__NR_fspick] = STR(fspick),
[__NR_pidfd_open] = STR(pidfd_open),
[__NR_clone] = STR(clone),
[__NR_close_range] = STR(close_range),
[__NR_openat] = STR(openat),
[__NR_pidfd_getfd] = STR(pidfd_getfd),
[__NR_faccessat] = STR(faccessat),
[__NR_process_madvise] = STR(process_madvise),
[__NR_epoll_pwait] = STR(epoll_pwait),
[__NR_mount_setattr] = STR(mount_setattr),
[__NR_quotactl_fd] = STR(quotactl_fd),
[__NR_landlock_create_ruleset] = STR(landlock_create_ruleset),
[__NR_landlock_add_rule] = STR(landlock_add_rule),
[__NR_landlock_restrict_self] = STR(landlock_restrict_self),
[__NR_memfd_secret] = STR(memfd_secret),
[__NR_process_mrelease] = STR(process_mrelease),
};
*/

#endif